### ISSUE TITLE
ERROR: Failed to download APKs

### ISSUE THREAD

**Issue by penserbjorne** [mvt-project/androidqf#12]
Hi!

I'm having troubles getting the applications from Samsung devices with Android 13.
This only happened on Samsung devices at this moment, I don't know if this is happening on other Android 13 devices, but reading on Internet it seems to happen since Android 11 (?).

```
Downloading copies of installed apps...
ERROR: Failed to download APKs: failed to retrieve list of installed packages: failed to launch `pm list packages` command: exit status 255
```

Also, trying the same command from terminal I got this:

```
$ adb shell pm list packages

Exception occurred while executing 'list':
java.lang.SecurityException: Shell does not have permission to access user 10
 com.android.server.am.ActivityManagerService.handleIncomingUser:14888 android.app.ActivityManager.handleIncomingUser:4802 com.android.server.pm.PackageManagerShellCommand.translateUserId:3510 
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:2672)
	at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:14888)
	at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:4802)
	at com.android.server.pm.PackageManagerShellCommand.translateUserId(PackageManagerShellCommand.java:3510)
	at com.android.server.pm.PackageManagerShellCommand.runListPackages(PackageManagerShellCommand.java:969)
	at com.android.server.pm.PackageManagerShellCommand.runListPackages(PackageManagerShellCommand.java:865)
	at com.android.server.pm.PackageManagerShellCommand.runList(PackageManagerShellCommand.java:724)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:226)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:6997)
	at android.os.Binder.shellCommand(Binder.java:1085)
	at android.os.Binder.onTransact(Binder.java:903)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4909)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:6981)
	at android.os.Binder.execTransactInternal(Binder.java:1321)
	at android.os.Binder.execTransact(Binder.java:1280)

```

The command can be run as primary user:

```
pm list packages --user 0
```

I don't know if this is a fix, but it helps for now.

Thanks!
P.

**Comment by besendorf** [comment]
I cant reproduce this on my Galaxy A54 5G with Android 14. Do you still have that issue? If so on what phone and Android version?

**Comment by besendorf** [comment]
I still cant reproduce on mine, which is a bit unlucky. Could you try this PR on those phones please?
https://github.com/mvt-project/androidqf/pull/71
